### PR TITLE
Add reactnative.gallery

### PR DESCRIPTION
**Pull request by xcarpentier**

### CODE REVIEW

**Comment by jondot** [comment]
Hi! Any idea when this is ready?

**Comment by xcarpentier** [comment]
I send you an email
(ie. ETA soon but 🤐 )

**Comment by xcarpentier** [comment]
@jondot Any news?

**Comment by jondot** [comment]
Apologies, probably just slipped away! let's add this in for now. Just LMK when it launches 😎

**Comment by xcarpentier** [comment]
Ok will let you know :)

**Comment by xcarpentier** [comment]
@jondot I’ve made some improvement: https://reactnative.gallery

What do you think?

**Pull request merged**
