### PR TITLE
add react-hook-hooker

### PR DESCRIPTION
**Pull request by fjcaetano**

### CODE REVIEW

**Comment by fjcaetano** [comment]
Is this error something on my side?

**Comment by pvinis** [comment]
https://github.com/fjcaetano/react-hook-hooker

**Comment by pvinis** [comment]
> Is this error something on my side?

No, it's a CI problem.

**Comment by fjcaetano** [comment]
Is there anything I need to do? Why did you comment with the link to the repo?

**Comment by pvinis** [comment]
Nothing to do about the CI stuff, the PR will be merged at some point.

I put the link because the PR template says:
```
<!--
Please also add a link to what you just added here.
Thank you.

Anywhere under here is perfect!
-->
```
😄

**Comment by fjcaetano** [comment]
Oh, my mistake! Thank you

**Pull request merged**
