### PR TITLE
update star & add to html

### PR DESCRIPTION
**Pull request by FuYaoDe**

### CODE REVIEW

**Comment by jondot** [comment]
Thanks! Is there a reason to include HTML?

**Comment by FuYaoDe** [comment]
There is no particular reason, I see a lack of it, the program will automatically generate that?

**Comment by jondot** [comment]
Yes, you know what, I think that was mistakenly included in one of the previous PRs.
I'll merge your changes and then I'll make sure to take out the HTML.
So nothing you should do, thanks! :)

**Comment by FuYaoDe** [comment]
Thanks ! I appreciated your time and effort on React Native.

**Pull request merged**
