### PR TITLE
Timeless release section

### PR DESCRIPTION
**Pull request by jhabdas**
Less maintenance. Evergreen list of releases.

### CODE REVIEW

**Comment by jondot** [comment]
@jhabdas thanks! I personally use the 'watch' feature to be able to stay up to date with releases, once we do this then the README will no longer experience new releases. What do you think? perhaps we merge this PR but still keep a latest version link so people stay up to date?

**Comment by jhabdas** [comment]
Hadn't thought of using watch for keeping up to date on releases. Not sure how we could ensure the README Releases stays up-to-date over time. But we could add a shield with the latest version number a la https://shields.io/ and link that to the list of RN releases. But, like DavidDM, it goes down occasionally. Happy to close and keep updating the Release section manually if you feel that'd be better.

**Comment by jondot** [comment]
You are definitely right the fact that we're replicating the version history bugs me as well, let's try doing this - let's try to remove all version history, but keep something like `Latest version: vX.X.X` and that will simply link to the latest version for anyone interested. What do you think?

**Comment by jhabdas** [comment]
Sounds like a plan.

**Pull request closed without merging**
