### PR TITLE
add ADB-auto-restarter && Fix travis validation

### PR DESCRIPTION
**Pull request by mahanhaz**
this is a very handy tools for android/React-native developers in case they are having problem with ADB's crashing problem while they are developing/testing/debugging with an actual device like me.
this will save alot of times.

### CODE REVIEW

**Comment by mahanhaz** [comment]
I also added another parameter to Httparty Head request to stop verifying the ssl incase of some Repositories.

**Comment by mahanhaz** [comment]
@jondot please merge it if it's ok, otherwise let me know the issue to fix
:)

**Comment by jondot** [comment]
Thanks! Looking at it now

**Comment by mahanhaz** [comment]
@jondot cheers mate

**Pull request merged**
