### PR TITLE
More article about native component

### PR DESCRIPTION
**Pull request by mactive**
you use react native more, the more native parts you will touch.
Need more advanced articles about this part.

### CODE REVIEW

**Comment by jondot** [comment]
Thanks!

**Comment by jondot** [comment]
One of the links is duplicated (see Travis build log), can you please fix?

**Comment by mactive** [comment]
Yeah, I have remote the duplicated link. and next i will find and write some Tutorial begins here http://xbay.github.io/2016/03/31/React-Native-NativeComponent/

**Comment by jondot** [comment]
Awesome!

**Pull request merged**
